# 1. The Network Doorway
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 30080
      targetPort: 8080

---
# 2. The Container Manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.1
          imagePullPolicy: IfNotPresent  # Tells K8s to use your local image, not the internet!
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5434/orders_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"