spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orders_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092