spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orders_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
      bootstrap-servers: kafka-service:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer